version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Moscow"
    labels:
      - "Type: Dependencies"
    versioning-strategy: "increase"
    rebase-strategy: "disabled"
